#!/bin/bash

python sdmf-scripts/makemakedoc.py "$@"

mkdir -p sdmf-output/

# format for LaTeX, if python succeeded
if [ $? -eq 0 ]
then
    for file in "variables.txt targets.txt intermediates.txt"
    do
	sed -i -e 's/;/ \& /g' -e 's/$/ \\\\/' ${file}
    done
else
    exit 1
fi

mv variables.txt sdmf-output/
mv targets.txt sdmf-output/
mv intermediates.txt sdmf-output/